// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9zmQgSAPIeyG9A8gtJc6O4h4YKcL2mLY',
    appId: '1:983555933528:web:c665aaf1549bd32d4dd12d',
    messagingSenderId: '983555933528',
    projectId: 'fyp-project-c3434',
    authDomain: 'fyp-project-c3434.firebaseapp.com',
    storageBucket: 'fyp-project-c3434.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDABIsLPAcNDvw-iYhnymmxH_mGrYAwT-8',
    appId: '1:983555933528:android:64af88c706d18f254dd12d',
    messagingSenderId: '983555933528',
    projectId: 'fyp-project-c3434',
    storageBucket: 'fyp-project-c3434.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSG60QuXdB2Us04FNcnIy_v2zmSTmNpk0',
    appId: '1:983555933528:ios:9da40cc797334f2e4dd12d',
    messagingSenderId: '983555933528',
    projectId: 'fyp-project-c3434',
    storageBucket: 'fyp-project-c3434.appspot.com',
    iosBundleId: 'com.example.petCareFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSG60QuXdB2Us04FNcnIy_v2zmSTmNpk0',
    appId: '1:983555933528:ios:f46bfd81bda56e434dd12d',
    messagingSenderId: '983555933528',
    projectId: 'fyp-project-c3434',
    storageBucket: 'fyp-project-c3434.appspot.com',
    iosBundleId: 'com.example.petCareFyp.RunnerTests',
  );
}
